config/routes.rb
Defaults::Application.routes.draw do
  devise_for :users

  resources :news do
    get "default", on: :collection
    put "set_default", on: :member
  end

  root to: "news#default"
end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :body, :title

  # See lib/acts_as_defaultable module
  include ActsAsDefaultable::Methods
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show, :default]

  def index
    @news = News.order("created_at DESC").page(params[:page]).per(5)
  end

  def show
    @news = News.find params[:id]
  end

  def new
    @news = News.new
  end

  def create
    @news = News.new params[:news]
    if @news.save
      redirect_to news_path(@news)
    else
      render "new"
    end
  end

  def edit
    @news = News.find params[:id]
  end

  def update
    @news = News.find params[:id]
    if @news.update_attributes params[:news]
      redirect_to news_path(@news)
    else
      render "edit"
    end
  end

  def destroy
    News.find(params[:id]).destroy
    redirect_to news_index_path
  end

  def default
    @news = News.default
    render "show"
  end

  def set_default
    @news = News.find params[:id]
    @news.default!
    redirect_to news_index_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title = head_title "Awesome News Feed"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    = stylesheet_link_tag     "application", media: :all
    = javascript_include_tag  "application"
    = csrf_meta_tag

  body
    .content.service-three
      .container
        .row
          .span8
            = link_to root_path, class: "brand" do
              h1
                ' News
                span.color Feed
            end
          .span4
            p.big.grey
              | Our news are the coolest you've ever seen, no doubt!
        .row
          .span1.offset11
            - if current_user
              = link_to "Logout", destroy_user_session_path, method: :delete
            - else
              = link_to "Login", new_user_session_path
        hr

        = yield

    footer
      .container
        .center
          p &copy; Dmitry Gritsay

app/views/news/_form.html.slim
h2 Create news
p.big Tell people what you've found out
hr

.row.make-post
  = simple_form_for @news, html: { class: "form-vertical" } do |f|
    .span8
      .well
        h5 Make news
        hr
        = f.input :title, label: false, placeholder: "Title goes here", input_html: { class: "input-xxlarge" }
        = f.input :body, label: false, placeholder: "Text goes here", input_html: { class: "input-xxlarge", rows: 7 }
    .span4
      .well
        h6 Actions
        hr
        = f.submit "Submit", class: "btn btn-primary"
        '
        button.btn Cancel


/ TODO: add delete if persisted

app/views/news/edit.html.slim
= render "form"

app/views/news/index.html.slim
- title "All news - Awesome News Feed"

h2.center Recent news

.tasks
  - @news.each do |news|
    .task
      h6
        = link_to news.title, news_path(news)
      p = truncate news.body, length: 255, separator: " "
      .tmeta
        i.icon-calendar
        = time_ago_in_words news.created_at
        '  ago -
        = link_to news_path(news) do
          i.icon-search
          | Read
        - if current_user
          '  -
          = link_to edit_news_path(news) do
            i.icon-pencil
            | Edit
          '  -
          = link_to news_path(news), method: :delete, confirm: "Are you sure?" do
            i.icon-remove
            | Remove
          '  -
          - if news.default?
            i.icon-pushpin
            | Default
          - else
            = link_to set_default_news_path(news), method: :put do
              i.icon-pushpin
              ' Set as default

= paginate @news

  /.task
  /  h6
  /    a href="#"
  /      | Op-Ed: Egypt’s Blood, America’s Complicity
  /  p Until the legitimate Morsi government is restored, American rhetoric about democracy will ring hollow.
  /  .tmeta
  /    i.icon-calendar
  /    '  2 minutes ago -
  /    a href="#"
  /      i.icon-search
  /      ' Read -
  /    a href="#"
  /      i.icon-pencil
  /      ' Edit -
  /    a href="#"
  /      i.icon-remove
  /      ' Remove -
  /    a href="#"
  /      i.icon-pushpin
  /      ' Set as default
  /
  /.task.cool
  /  h6 Admin, default news
  /  p Body
  /  .tmeta
  /    i.icon-calendar
  /    '  25 minutes ago -
  /    a href="#"
  /      i.icon-search
  /      ' Read -
  /    a href="#"
  /      i.icon-pencil
  /      ' Edit -
  /    a href="#"
  /      i.icon-remove
  /      ' Remove -
  /    i.icon-pushpin
  /    | Default
  /
  /.task
  /  h6 Guest
  /  p Body
  /  .tmeta
  /    i.icon-calendar
  /    '  25 minutes ago -
  /    a href="#"
  /      i.icon-search
  /      ' Read

app/views/news/new.html.slim
= render "form"

app/views/news/show.html.slim
- title "#{@news.title} - Awesome News Feed"
.center
  h2 Breaking news!

  .breaking-news
    .container
      .row
        .span12
          h2 = @news.title
          h6 = @news.body
  .row
    .span12
      i.icon-calendar
      = time_ago_in_words @news.created_at
      '  ago
      - if current_user
        '  -
        = link_to edit_news_path(@news) do
          i.icon-pencil
          | Edit
        '  -
        = link_to news_path(@news), method: :delete, confirm: "Are you sure?" do
          i.icon-remove
          | Remove
        '  -
        - if @news.default?
          i.icon-pushpin
          | Default
        - else
          = link_to set_default_news_path(@news), method: :put do
            i.icon-pushpin
            ' Set as default

  = link_to "Read all news", news_index_path, class: "btn btn-large"